(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), fmt=d=>d?d.split('-').reverse().join('.'):'';
const TYPES={socket:{name:'Rozete',cable:'Cu 3x2,5',breaker:'B16',phases:1},light:{name:'Gaismeklis',cable:'Cu 3x1,5',breaker:'B13',phases:1},three:{name:'3F rozete',cable:'Cu 5x2,5',breaker:'C16',phases:3},equipment:{name:'Iekārta',cable:'Cu 3x2,5',breaker:'B16',phases:1},other:{name:'Cits',cable:'',breaker:'',phases:1}};
const MODS={iso:'Izolācijas pretestība',loop:'Cilpa fāze–nulle un īsslēguma strāva',continuity:'Zemējuma nepārtrauktība',earth:'Zemējuma kontūra pretestība',lightning:'Zibensaizsardzība'};
const defaults=()=>({version:5,fields:{customer:'',customerPhone:'',customerEmail:'',objectName:'',address:'',workArea:'Viss objekts',actDate:'',measureDate:'',temperature:'',humidity:'',worker:'Marks Elarts',workerPhone:'+371 27 655 228',workerEmail:'marks.elarts@gmail.com',meterName:'Fluke',meterType:'1653',meterSerial:'8619046',calibrationNo:'787595',thermalCamera:'FLIR C3-X',thermalSerial:'905028092',thermalCalibrationNo:'T1395K23'},mods:{iso:true,loop:true,continuity:true,earth:false,lightning:false},floors:[],special:{earth:[{id:uid(),name:'Zemējuma kontūrs',value:'',result:'Atbilst'}],lightning:[{id:uid(),name:'Zibensaizsardzības sistēmas elements',value:'',result:'Atbilst'}]},certificates:[],photos:[]});
let state=defaults(), saveTimer, installPrompt;
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function openDB(){return new Promise((ok,no)=>{const q=indexedDB.open('merijumi-db',1);q.onupgradeneeded=()=>q.result.createObjectStore('reports');q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function save(){clearTimeout(saveTimer);$('#saveStatus').textContent='Saglabā...';saveTimer=setTimeout(async()=>{try{const db=await openDB(),tx=db.transaction('reports','readwrite');tx.objectStore('reports').put(state,'current');await new Promise((a,b)=>{tx.oncomplete=a;tx.onerror=()=>b(tx.error)});$('#saveStatus').textContent='Saglabāts telefonā'}catch(e){$('#saveStatus').textContent='Neizdevās saglabāt';console.error(e)}},250)}
async function load(){try{const db=await openDB(),tx=db.transaction('reports'),q=tx.objectStore('reports').get('current');const data=await new Promise((a,b)=>{q.onsuccess=()=>a(q.result);q.onerror=()=>b(q.error)});if(data)state=Object.assign(defaults(),data)}catch(e){console.error(e)}migrate();if(!state.fields.actDate){const d=new Date().toISOString().slice(0,10);state.fields.actDate=state.fields.measureDate=d}render()}
function migrate(){state.version=5;state.certificates=state.certificates||[];state.photos=state.photos||[];state.special=state.special||defaults().special;state.floors=state.floors||[];for(const {d} of allDevices()){d.phase=d.phase||'L1';d.result=d.result||'Atbilst'}for(const p of state.photos){p.current=p.current||'';p.result=p.result||'Atbilst'}}
function device(type,name){const p=TYPES[type];return{id:uid(),type,name:name||p.name,cable:p.cable,breaker:p.breaker,board:'GSS',voltage:p.phases===3?'400/230':'230',phases:p.phases,phase:'L1',iso:'>500',continuity:'<0.1',result:'Atbilst',short1:'',short2:'',short3:'',loop1:'',loop2:'',loop3:''}}
function render(){Object.entries(state.fields).forEach(([k,v])=>{const e=$(`[data-field="${k}"]`);if(e&&document.activeElement!==e)e.value=v});$('#heroTitle').textContent=state.fields.objectName||'Jauna elektromērījumu atskaite';renderChoices();renderBuilding();renderMeasurements();renderAttachments();validate()}
function renderChoices(){$('#measurementChoices').innerHTML=Object.entries(MODS).map(([k,n])=>`<label class="choice"><input type="checkbox" data-mod="${k}" ${state.mods[k]?'checked':''}><span><b>${esc(n)}</b></span></label>`).join('')}
function renderBuilding(){const root=$('#building');root.innerHTML=state.floors.map(f=>`<div class="floor"><div class="floor-head"><input value="${esc(f.name)}" data-floor-name="${f.id}" aria-label="Stāva nosaukums"><button class="small danger" data-remove-floor="${f.id}">Dzēst</button></div><div class="floor-body"><div class="inline-form"><input placeholder="Jauna telpa" data-room-input="${f.id}"><button data-add-room="${f.id}">Pievienot telpu</button></div>${f.rooms.map(r=>`<div class="room"><div class="room-head"><input value="${esc(r.name)}" data-room-name="${r.id}"><button class="small danger" data-remove-room="${f.id}|${r.id}">Dzēst</button></div><div>${r.devices.map(d=>`<div class="device-chip"><span><b>${esc(d.name)}</b> · ${esc(TYPES[d.type]?.name||'Ierīce')}</span><button class="danger" data-remove-device="${f.id}|${r.id}|${d.id}">Dzēst</button></div>`).join('')||'<p class="hint">Nav ierīču.</p>'}</div><div class="add-device"><input placeholder="Ierīces nosaukums" data-device-name="${r.id}"><select data-device-type="${r.id}">${Object.entries(TYPES).map(([k,p])=>`<option value="${k}">${p.name}</option>`).join('')}</select><input type="number" min="1" value="1" data-device-qty="${r.id}" aria-label="Daudzums"><button data-add-device="${f.id}|${r.id}">Pievienot</button></div></div>`).join('')}</div></div>`).join('')||'<p class="hint">Pievieno pirmo stāvu.</p>'}
function allDevices(){return state.floors.flatMap(f=>f.rooms.flatMap(r=>r.devices.map(d=>({f,r,d}))))}
function carryForwardLoopValues(){let filled=0;for(const f of state.floors)for(const r of f.rooms){const last={short1:'',short2:'',short3:'',loop1:'',loop2:'',loop3:''};for(const d of r.devices)for(const key of Object.keys(last)){if(String(d[key]??'').trim())last[key]=d[key];else if(last[key]!==''&&(d.phases===3||key.endsWith('1'))){d[key]=last[key];filled++}}}return filled}
function renderMeasurements(){const root=$('#measurements'), enabled=state.mods.iso||state.mods.loop||state.mods.continuity;root.innerHTML=enabled?state.floors.map(f=>f.rooms.map(r=>r.devices.length?`<div class="measurement-room"><h3>${esc(f.name)} · ${esc(r.name)}</h3>${r.devices.map(d=>`<div class="measure-card"><div class="measure-title"><b>${esc(d.name)}</b><span>${esc(TYPES[d.type]?.name)}</span></div><div class="measurement-fields"><label>Sadalne<input data-dev="${d.id}|board" value="${esc(d.board)}"></label><label>Kabelis<input data-dev="${d.id}|cable" value="${esc(d.cable)}"></label><label>Aizsardzība<input data-dev="${d.id}|breaker" value="${esc(d.breaker)}"></label><label>Spriegums V<input data-dev="${d.id}|voltage" value="${esc(d.voltage)}"></label>${d.phases===1?`<label>Fāze<select data-dev="${d.id}|phase">${['L1','L2','L3'].map(x=>`<option ${d.phase===x?'selected':''}>${x}</option>`).join('')}</select></label>`:''}${state.mods.iso?`<label>Izolācija MΩ<input data-dev="${d.id}|iso" value="${esc(d.iso)}"></label>`:''}${state.mods.continuity?`<label>PE saite Ω<input data-dev="${d.id}|continuity" value="${esc(d.continuity)}"></label>`:''}${state.mods.loop?phaseFields(d):''}<label>Atzinums<select data-dev="${d.id}|result"><option ${d.result==='Atbilst'?'selected':''}>Atbilst</option><option ${d.result==='Neatbilst'?'selected':''}>Neatbilst</option></select></label></div></div>`).join('')}</div>`:'').join('')).join(''):'<p class="hint">Ierīču mērījumu sadaļas nav izvēlētas.</p>';renderSpecial()}
function phaseFields(d){if(d.phases===3)return [1,2,3].map(n=>`<label>Iīss L${n} A<input inputmode="decimal" data-dev="${d.id}|short${n}" value="${esc(d['short'+n])}"></label><label>Zs L${n} Ω<input inputmode="decimal" data-dev="${d.id}|loop${n}" value="${esc(d['loop'+n])}"></label>`).join('');return `<label>Iīss ${esc(d.phase||'L1')} A<input inputmode="decimal" data-dev="${d.id}|short1" value="${esc(d.short1)}"></label><label>Zs ${esc(d.phase||'L1')} Ω<input inputmode="decimal" data-dev="${d.id}|loop1" value="${esc(d.loop1)}"></label>`}
function renderSpecial(){let h='';for(const k of ['earth','lightning'])if(state.mods[k])h+=`<div class="measurement-room"><h3>${MODS[k]}</h3>${state.special[k].map(x=>`<div class="measure-card measurement-fields"><label>Vieta / elements<input data-special="${k}|${x.id}|name" value="${esc(x.name)}"></label><label>Pretestība Ω<input inputmode="decimal" data-special="${k}|${x.id}|value" value="${esc(x.value)}"></label><label>Atzinums<select data-special="${k}|${x.id}|result"><option ${x.result==='Atbilst'?'selected':''}>Atbilst</option><option ${x.result==='Neatbilst'?'selected':''}>Neatbilst</option></select></label><button class="danger" data-remove-special="${k}|${x.id}">Dzēst</button></div>`).join('')}<button class="secondary" data-add-special="${k}">Pievienot mērījuma vietu</button></div>`;$('#specialMeasurements').innerHTML=h}
function renderAttachments(){const cards=(a,type)=>a.map(x=>`<div class="thumb"><img src="${x.data}" alt=""><div class="thumb-body"><input value="${esc(x.description)}" data-attachment="${type}|${x.id}|description" aria-label="Apraksts">${type==='photos'&&x.type==='thermal'?`<input value="${esc(x.current)}" data-attachment="${type}|${x.id}|current" aria-label="Izmērītā strāva" placeholder="Izmērītā strāva, A"><select data-attachment="${type}|${x.id}|result" aria-label="Atzinums"><option ${x.result==='Atbilst'?'selected':''}>Atbilst</option><option ${x.result==='Neatbilst'?'selected':''}>Neatbilst</option></select>`:''}<button class="danger" data-remove-attachment="${type}|${x.id}">Dzēst</button></div></div>`).join('');$('#certificates').innerHTML=cards(state.certificates,'certificates');$('#photos').innerHTML=cards(state.photos,'photos')}
function validate(){const m=[];if(!state.fields.customer)m.push('nav pasūtītāja');if(!state.fields.address)m.push('nav adreses');if(!state.floors.length)m.push('nav stāvu');if(!allDevices().length)m.push('nav ierīču');if(!Object.values(state.mods).some(Boolean))m.push('nav izvēlētu mērījumu');$('#validation').className=m.length?'warn':'ok';$('#validation').textContent=m.length?'Pirms gala atskaites ieteicams aizpildīt: '+m.join(', ')+'.':'Pamatinformācija ir aizpildīta. Atskaiti var eksportēt.'}
function reportHTML(){const pages=[];pages.push(coverPage());state.certificates.forEach(c=>pages.push(`<section class="report-page certificate"><img src="${c.data}" alt="${esc(c.description||'Sertifikāts')}"></section>`));pages.push(actPage());if(state.mods.iso)pages.push(...measurementPages('1. Elektroinstalācijas izolācijas pretestības mērījumu rezultāti:','iso'));if(state.mods.loop)pages.push(...measurementPages('2. Cilpas “fāze–nulle” pilnās pretestības mērījumu rezultāti:','loop'));if(state.mods.earth)pages.push(simpleMeasurementPage('3. Zemējumietaises pretestības mērījumu rezultāti:',state.special.earth));if(state.mods.continuity)pages.push(...measurementPages('4. Zemējumvadu nepārtrauktības saites pretestības mērījumu rezultāti','continuity'));if(state.mods.lightning)pages.push(simpleMeasurementPage('5. Zibensaizsardzības sistēmas elementu pretestības mērījumu rezultāti:',state.special.lightning));if(state.photos.some(p=>p.type==='thermal'))pages.push(contactActPage());state.photos.forEach((p,i)=>pages.push(photoPage(p,i)));return pages.join('')}
function coverPage(){return `<section class="report-page cover"><div class="cover-customer"><p><b>Pasūtītājs:</b>&nbsp; ${esc(state.fields.customer)}</p><p><b>Objekts:</b>&nbsp; ${esc(state.fields.objectName?`“${state.fields.objectName}”, `:'')}${esc(state.fields.address)}</p></div><h1>Elektrotehniskā dokumentācija</h1><div class="cover-worker"><p><b>Mērījumus veica:</b> ${esc(state.fields.worker)}</p><p><b>Kontaktinformācija:</b></p><p>${esc(state.fields.workerPhone)}</p><p>${esc(state.fields.workerEmail)}</p></div></section>`}
function actPage(){const workTitle='Elektroinstalācijas izolācijas pretestības, cilpas “fāze–nulle” pilnās pretestības, zemējumietaises pretestības, zemējumvada nepārtrauktības saites un zibensaizsardzības sistēmas pārbaudes akts';return `<section class="report-page act-page"><h1>${workTitle}</h1><table class="form-table"><tr><th>Akta datums</th><td>${fmt(state.fields.actDate)}</td></tr><tr><th>Objekta atbildīgā persona</th><td>${esc(state.fields.customer)}${state.fields.customerPhone?' · '+esc(state.fields.customerPhone):''}${state.fields.customerEmail?' · '+esc(state.fields.customerEmail):''}</td></tr><tr><th>Objekta nosaukums un adrese</th><td>${esc(state.fields.objectName)}${state.fields.objectName&&state.fields.address?', ':''}${esc(state.fields.address)}</td></tr><tr><th>Darba norises vieta</th><td>${esc(state.fields.workArea)}</td></tr><tr><th>Darba veicējs</th><td>${esc(state.fields.worker)}</td></tr></table><h3>Mēraparāta tehniskie dati</h3><table><thead><tr><th>Nosaukums</th><th>Tips</th><th>Numurs</th><th>Mērapazons</th><th>Kalibrēšanas sertifikāta numurs</th></tr></thead><tbody><tr><td>${esc(state.fields.meterName)}</td><td>${esc(state.fields.meterType)}</td><td>${esc(state.fields.meterSerial)}</td><td>R<sub>izol.</sub>: 0,01 MΩ līdz 1999 MΩ<br>Cilpa “fāze–0”: 0,01 Ω līdz 2000 Ω<br>R<sub>zemējuma</sub>: līdz 2000 Ω<br>I<sub>noplūdes</sub>: līdz 20 kA</td><td>Nr. ${esc(state.fields.calibrationNo)}</td></tr><tr><td>${esc(state.fields.thermalCamera)}</td><td>Termokamera</td><td>${esc(state.fields.thermalSerial)}</td><td>(−20 ÷ 150) °C</td><td>Nr. ${esc(state.fields.thermalCalibrationNo)}</td></tr></tbody></table><h3>Klimatiskie apstākļi mērījumu veikšanas gaitā</h3><table><thead><tr><th>Darba veikšanas datums</th><th>Gaisa temperatūra (°C)</th><th>Gaisa mitrums (%)</th></tr></thead><tbody><tr><td>${fmt(state.fields.measureDate)}</td><td>${esc(state.fields.temperature)}</td><td>${esc(state.fields.humidity)}</td></tr></tbody></table><p>Akts sastādīts par to, ka darba veicējs objektā veica (atzīmēt ar X):</p><table class="checks"><tbody>${Object.entries(MODS).map(([k,n])=>`<tr><td>${state.mods[k]?'X':''}</td><td>${esc(n)} mērījumus</td></tr>`).join('')}</tbody></table></section>`}
function flatRows(){const out=[];let n=1;const usedFloors=state.floors.filter(f=>f.rooms.some(r=>r.devices.length));for(const f of usedFloors){if(usedFloors.length>1&&f.name)out.push({kind:'group',n:n++,label:f.name});for(const r of f.rooms){if(!r.devices.length)continue;out.push({kind:'group',n:n++,label:r.name});for(const d of r.devices)out.push({kind:'device',n:n++,d})}}return out}
function chunks(rows){const out=[];let i=0,limit=32;while(i<rows.length){out.push(rows.slice(i,i+limit));i+=limit;limit=46}return out.length?out:[[]]}
function measurementPages(title,kind){const parts=chunks(flatRows());return parts.map((part,i)=>`<section class="report-page measurement-page ${kind}">${i===0?`<h2>${title}</h2>`:''}${measurementTable(kind,part)}${i===parts.length-1?sig():''}</section>`)}
function measurementTable(kind,items){const colCount=kind==='continuity'?4:kind==='iso'?15:12;return `<table class="measurement-table ${kind}-table"><thead>${tableHead(kind)}</thead><tbody>${items.map(x=>x.kind==='group'?`<tr class="room-row"><td>${x.n}</td><td colspan="${colCount-1}">${esc(x.label)}</td></tr>`:deviceRow(kind,x.d,x.n)).join('')}</tbody></table>`}
function tableHead(kind){if(kind==='iso')return `<tr><th rowspan="3">Nr.<br>p.k.</th><th rowspan="3">Tīkla tips,<br>elektroinstalācijas<br>atrašanās vieta</th><th rowspan="3">Kabeļa marka,<br>dzīslu skaits,<br>šķērsgriezums</th><th rowspan="3">Pārbaudes<br>spriegums,<br>V</th><th colspan="10">Izolācijas pretestība, MΩ</th><th rowspan="3">Atzinums</th></tr><tr><th>L1-PE</th><th>L2-PE</th><th>L3-PE</th><th>N-PE</th><th>L1-N</th><th>L2-N</th><th>L3-N</th><th>L1-L2</th><th>L1-L3</th><th>L2-L3</th></tr><tr>${'<th></th>'.repeat(10)}</tr>`;if(kind==='loop')return `<tr><th rowspan="3">Nr.<br>p.k.</th><th rowspan="3">Tīkla tips,<br>elektroinstalācijas<br>atrašanās vieta</th><th rowspan="3">Sadales<br>numurs</th><th rowspan="3">Tīkla<br>spriegums,<br>V</th><th rowspan="3">Aizsardzības<br>aparāta tips,<br>nominālā strāva</th><th colspan="3">Vienfāzes īsslēguma strāva (A)</th><th colspan="3">Cilpas “fāze–nulle” pilnā pretestība, Ω</th><th rowspan="3">Atzinums</th></tr><tr><th colspan="3">I<sub>īss</sub> (L1/L2/L3)</th><th colspan="3">Z<sub>s</sub> (L1/L2/L3)</th></tr><tr><th>L1</th><th>L2</th><th>L3</th><th>L1</th><th>L2</th><th>L3</th></tr>`;return `<tr><th colspan="4">Zemējuma nepārtrauktības mērījumu rezultāti</th></tr><tr><th>Nr.<br>p.k.</th><th>Elektroiekārtas atrašanās vieta un pārbaudes vieta</th><th>Pretestība, Ω</th><th>Atzinums</th></tr>`}
function phaseValues(d,prefix){if(d.phases===3)return [d[prefix+'1'],d[prefix+'2'],d[prefix+'3']];const a=['','',''],ix=Math.max(0,['L1','L2','L3'].indexOf(d.phase||'L1'));a[ix]=d[prefix+'1'];return a}
function deviceRow(kind,d,n){if(kind==='iso'){const i=d.iso||'',ix=Math.max(0,['L1','L2','L3'].indexOf(d.phase||'L1')),vals=Array(10).fill('');if(d.phases===3)vals.fill(i);else{vals[ix]=i;vals[3]=i;vals[4+ix]=i}return `<tr><td>${n}</td><td>${esc(d.name)}</td><td>${esc(d.cable)}</td><td>500</td>${vals.map(v=>`<td>${esc(v)}</td>`).join('')}<td>${esc(d.result)}</td></tr>`}if(kind==='loop'){const shorts=phaseValues(d,'short'),loops=phaseValues(d,'loop');return `<tr><td>${n}</td><td>${esc(d.name)}</td><td>${esc(d.board)}</td><td>${esc(d.voltage)}</td><td>${esc(d.breaker)}</td>${[...shorts,...loops].map(v=>`<td>${esc(v)}</td>`).join('')}<td>${esc(d.result)}</td></tr>`}return `<tr><td>${n}</td><td>${esc(d.name)}</td><td>${esc(d.continuity)}</td><td>${esc(d.result)}</td></tr>`}
function simpleMeasurementPage(title,data){return `<section class="report-page measurement-page"><h2>${title}</h2><table class="measurement-table simple-table"><thead><tr><th>Nr.<br>p.k.</th><th>Vieta / elements</th><th>Pretestība, Ω</th><th>Atzinums</th></tr></thead><tbody>${data.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td>${esc(x.value)}</td><td>${esc(x.result)}</td></tr>`).join('')}</tbody></table>${sig()}</section>`}
const sig=()=>`<div class="signature"><div><p>Darba veicējs:</p><p>Akta eksemplāru<br>saņēma:</p></div><div class="sig-lines"><p>__________________________<br><small>(paraksts)</small></p><p>__________________________<br><small>(paraksts)</small></p></div><div class="sig-lines"><p>${esc(state.fields.worker)}<br><small>(vārds, uzvārds)</small></p><p>__________________________<br><small>(vārds, uzvārds)</small></p></div></div>`;
function contactActPage(){const thermal=state.photos.map((p,i)=>({p,i})).filter(x=>x.p.type==='thermal');return `<section class="report-page contact-act"><h1>Elektroinstalācijas kontaktsavienojumu akts</h1><p>Šis akts sastādīts par to, ka darba veicējs veica elektroinstalācijas kontaktsavienojumu pārbaudi, kuras rezultātā konstatēts:</p><table><thead><tr><th>Nr. p.k.</th><th>Mērījuma vieta</th><th>Caur kontaktu plūstošā strāva (A)</th><th>Mērījuma attēla numurs</th><th>Attēla dabā ar norādi uz problemātisko savienojumu</th><th>Atzinums</th></tr></thead><tbody>${thermal.map((x,j)=>{const ordinary=state.photos.findIndex((p,k)=>k>x.i&&p.type==='ordinary'&&(!p.description||p.description===x.p.description));return `<tr><td>${j+1}</td><td>${esc(x.p.description||'—')}</td><td>${esc(x.p.current||'—')}</td><td>${x.i+1}</td><td>${ordinary>=0?ordinary+1:'—'}</td><td>${esc(x.p.result||'Atbilst')}</td></tr>`}).join('')}</tbody></table>${sig()}</section>`}
function photoPage(p,i){if(p.type==='scheme')return `<section class="report-page photo-page scheme-page"><img src="${p.data}" alt=""><h2>${esc(p.description||'Sadalne')} Shēma</h2></section>`;return `<section class="report-page photo-page"><h2>${esc(p.description||'')}</h2><img src="${p.data}" alt=""><p>Attēls nr. ${i+1}</p></section>`}
async function compress(file){return new Promise((ok,no)=>{const r=new FileReader;r.onerror=no;r.onload=()=>{const im=new Image;im.onload=()=>{const max=1800,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);ok(c.toDataURL('image/jpeg',.82))};im.onerror=no;im.src=r.result};r.readAsDataURL(file)})}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function filename(ext){return (state.fields.objectName||state.fields.address||'elektromerijumu_atskaite').replace(/[^\p{L}\p{N}]+/gu,'_').replace(/^_|_$/g,'')+'.'+ext}
async function exportDocx(){
  if(!window.docx){toast('DOCX modulis vēl nav ielādēts. Pārbaudi internetu.');return}
  toast('Veido DOCX failu...');
  const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,ImageRun,WidthType,AlignmentType,VerticalAlign,BorderStyle}=window.docx;
  const children=[];
  const borders={top:{style:BorderStyle.SINGLE,size:4,color:'000000'},bottom:{style:BorderStyle.SINGLE,size:4,color:'000000'},left:{style:BorderStyle.SINGLE,size:4,color:'000000'},right:{style:BorderStyle.SINGLE,size:4,color:'000000'},insideHorizontal:{style:BorderStyle.SINGLE,size:4,color:'000000'},insideVertical:{style:BorderStyle.SINGLE,size:4,color:'000000'}};
  const p=(text,opt={})=>new Paragraph({alignment:opt.align||AlignmentType.LEFT,spacing:{before:opt.before||0,after:opt.after??80,line:opt.line||220},children:[new TextRun({text:String(text??''),bold:!!opt.bold,size:opt.size||18,font:'Arial',italics:!!opt.italics})]});
  const title=(text,size=22)=>p(text,{bold:true,size,align:AlignmentType.CENTER,after:180});
  const cell=(text,opt={})=>new TableCell({columnSpan:opt.span,verticalAlign:VerticalAlign.CENTER,margins:{top:35,bottom:35,left:35,right:35},children:[p(text,{bold:!!opt.bold,size:opt.size||12,align:opt.align||AlignmentType.CENTER,after:0,line:150})]});
  const row=cells=>new TableRow({children:cells});
  const table=(heads,data,opt={})=>new Table({width:{size:100,type:WidthType.PERCENTAGE},borders,rows:[...(opt.noHeader?[]:[row(heads.map(x=>cell(x,{bold:true,size:opt.headSize||11})))]),...data.map(r=>row(r.map(x=>cell(x,{size:opt.size||11,align:typeof x==='string'&&x.length>18?AlignmentType.LEFT:AlignmentType.CENTER}))))]});
  const page=()=>children.push(new Paragraph({pageBreakBefore:true,spacing:{after:0},children:[]}));
  const signature=()=>children.push(p('',{after:240}),table(['Darba veicējs:','(paraksts)','(vārds, uzvārds)'],[[state.fields.worker,'__________________',state.fields.worker],['Akta eksemplāru saņēma:','__________________','__________________']],{size:12,headSize:12}));
  children.push(p('Pasūtītājs:  '+state.fields.customer,{bold:true,size:20,after:280}),p('Objekts:  '+(state.fields.objectName?'“'+state.fields.objectName+'”, ':'')+state.fields.address,{bold:true,size:20}),p('',{after:1200}),title('Elektrotehniskā dokumentācija',28),p('',{after:1500}),p('Mērījumus veica: '+state.fields.worker,{bold:true,size:20,after:500}),p('Kontaktinformācija:',{bold:true,size:18}),p(state.fields.workerPhone,{size:18}),p(state.fields.workerEmail,{size:18}));
  for(const c of state.certificates){page();const s=await imageDimensions(c.data,690,930);children.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:0},children:[new ImageRun({data:dataBytes(c.data),transformation:s,type:'jpg'})]}))}
  page();children.push(title('Elektroinstalācijas izolācijas pretestības, cilpas “fāze–nulle” pilnās pretestības, zemējumietaises pretestības, zemējuma nepārtrauktības saites un zibensaizsardzības sistēmas pārbaudes akts',20),table([],[["Akta datums",fmt(state.fields.actDate)],['Objekta atbildīgā persona',state.fields.customer+' '+state.fields.customerPhone],['Objekta nosaukums un adrese',state.fields.objectName+', '+state.fields.address],['Darba norises vieta',state.fields.workArea],['Darba veicējs',state.fields.worker]],{size:13,noHeader:true}),p('Mēraparāta tehniskie dati',{bold:true,size:15,before:120}),table(['Nosaukums','Tips','Numurs','Mērapazons','Kalibrēšanas sertifikāta numurs'],[[state.fields.meterName,state.fields.meterType,state.fields.meterSerial,'Rizol. 0,01 MΩ–1999 MΩ; cilpa 0,01 Ω–2000 Ω; Rzem. līdz 2000 Ω; I līdz 20 kA','Nr. '+state.fields.calibrationNo],[state.fields.thermalCamera,'Termokamera',state.fields.thermalSerial,'−20 ÷ 150 °C','Nr. '+state.fields.thermalCalibrationNo]],{size:11,headSize:11}),p('Klimatiskie apstākļi mērījumu veikšanas gaitā',{bold:true,size:15,before:120}),table(['Darba veikšanas datums','Gaisa temperatūra (°C)','Gaisa mitrums (%)'],[[fmt(state.fields.measureDate),state.fields.temperature,state.fields.humidity]],{size:12,headSize:12}),p('Akts sastādīts par to, ka darba veicējs objektā veica (atzīmēt ar X):',{size:13,before:120}),table(['X','Mērījuma veids'],Object.entries(MODS).map(([k,n])=>[state.mods[k]?'X':'',n+' mērījumus']),{size:12,headSize:12}));
  const addMeasurement=(kind,heading)=>{const heads=kind==='iso'?['Nr.','Atrašanās vieta','Kabelis','U, V','L1-PE','L2-PE','L3-PE','N-PE','L1-N','L2-N','L3-N','L1-L2','L1-L3','L2-L3','Atzinums']:kind==='loop'?['Nr.','Atrašanās vieta','Sadalne','U, V','Aizsardzība','Iīss L1','L2','L3','Zs L1','L2','L3','Atzinums']:['Nr.','Atrašanās vieta / pārbaudes vieta','Pretestība, Ω','Atzinums'];const parts=chunks(flatRows());parts.forEach((part,pi)=>{page();if(pi===0)children.push(title(heading,18));const data=part.map(x=>{if(x.kind==='group')return [x.n,x.label,...Array(heads.length-2).fill('')];const d=x.d;if(kind==='iso'){const ix=Math.max(0,['L1','L2','L3'].indexOf(d.phase||'L1')),v=Array(10).fill('');if(d.phases===3)v.fill(d.iso);else{v[ix]=d.iso;v[3]=d.iso;v[4+ix]=d.iso}return [x.n,d.name,d.cable,'500',...v,d.result]}if(kind==='loop')return [x.n,d.name,d.board,d.voltage,d.breaker,...phaseValues(d,'short'),...phaseValues(d,'loop'),d.result];return [x.n,d.name,d.continuity,d.result]});children.push(table(heads,data,{size:kind==='continuity'?12:9,headSize:kind==='continuity'?11:8}));if(pi===parts.length-1)signature()})};
  if(state.mods.iso)addMeasurement('iso','1. Elektroinstalācijas izolācijas pretestības mērījumu rezultāti:');
  if(state.mods.loop)addMeasurement('loop','2. Cilpas “fāze–nulle” pilnās pretestības mērījumu rezultāti:');
  const addSimple=(heading,data)=>{page();children.push(title(heading,18),table(['Nr.','Vieta / elements','Pretestība, Ω','Atzinums'],data.map((x,i)=>[i+1,x.name,x.value,x.result]),{size:12,headSize:11}));signature()};
  if(state.mods.earth)addSimple('3. Zemējumietaises pretestības mērījumu rezultāti:',state.special.earth);
  if(state.mods.continuity)addMeasurement('continuity','4. Zemējuma nepārtrauktības mērījumu rezultāti');
  if(state.mods.lightning)addSimple('5. Zibensaizsardzības sistēmas elementu pretestības mērījumu rezultāti:',state.special.lightning);
  if(state.photos.some(x=>x.type==='thermal')){page();children.push(title('Elektroinstalācijas kontaktsavienojumu akts',22),p('Šis akts sastādīts par to, ka darba veicējs veica elektroinstalācijas kontaktsavienojumu pārbaudi, kuras rezultātā konstatēts:',{size:17,align:AlignmentType.CENTER}));const thermals=state.photos.map((x,i)=>({x,i})).filter(y=>y.x.type==='thermal');children.push(table(['Nr.','Mērījuma vieta','Caur kontaktu plūstošā strāva (A)','Mērījuma attēla Nr.','Attēla dabā Nr.','Atzinums'],thermals.map((y,j)=>{const ordinary=state.photos.findIndex((x,k)=>k>y.i&&x.type==='ordinary'&&(!x.description||x.description===y.x.description));return [j+1,y.x.description,y.x.current||'—',y.i+1,ordinary>=0?ordinary+1:'—',y.x.result||'Atbilst']}),{size:11,headSize:10}));signature()}
  for(let i=0;i<state.photos.length;i++){const x=state.photos[i];page();if(x.type!=='scheme')children.push(title(x.description||'',18));const s=await imageDimensions(x.data,690,x.type==='scheme'?650:720);children.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:120,after:120},children:[new ImageRun({data:dataBytes(x.data),transformation:s,type:'jpg'})]}),title(x.type==='scheme'?(x.description||'Sadalne')+' Shēma':'Attēls nr. '+(i+1),14))}
  const doc=new Document({styles:{default:{document:{run:{font:'Arial',size:18},paragraph:{spacing:{after:80}}}}},sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:720,right:720,bottom:720,left:720}}},children}]});
  download(await Packer.toBlob(doc),filename('docx'));toast('DOCX fails sagatavots');
}
function imageDimensions(data,maxWidth,maxHeight){return new Promise(resolve=>{const im=new Image;im.onload=()=>{const s=Math.min(maxWidth/im.width,maxHeight/im.height);resolve({width:Math.round(im.width*s),height:Math.round(im.height*s)})};im.onerror=()=>resolve({width:maxWidth,height:Math.round(maxWidth*.72)});im.src=data})}
function dataBytes(url){const b=atob(url.split(',')[1]),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
document.addEventListener('input',e=>{if(e.target.dataset.field)state.fields[e.target.dataset.field]=e.target.value;if(e.target.dataset.mod)state.mods[e.target.dataset.mod]=e.target.checked;if(e.target.dataset.floorName){const f=state.floors.find(x=>x.id===e.target.dataset.floorName);if(f)f.name=e.target.value}if(e.target.dataset.roomName){for(const f of state.floors){const r=f.rooms.find(x=>x.id===e.target.dataset.roomName);if(r)r.name=e.target.value}}if(e.target.dataset.dev){const[id,k]=e.target.dataset.dev.split('|'),x=allDevices().find(y=>y.d.id===id);if(x)x.d[k]=e.target.value}if(e.target.dataset.special){const[k,id,p]=e.target.dataset.special.split('|'),x=state.special[k].find(y=>y.id===id);if(x)x[p]=e.target.value}if(e.target.dataset.attachment){const[k,id,p='description']=e.target.dataset.attachment.split('|'),x=state[k].find(y=>y.id===id);if(x)x[p]=e.target.value}save();validate()});
document.addEventListener('change',e=>{if(e.target.dataset.mod){renderMeasurements();save()}if(e.target.dataset.dev?.endsWith('|phase')){renderMeasurements();save()}});
function fillBeforeExport(){const n=carryForwardLoopValues();if(n){renderMeasurements();save();toast(`Aizpildītas ${n} tukšas vērtības`)}}
document.addEventListener('click',e=>{const t=e.target;if(t.id==='todayBtn'){const d=new Date().toISOString().slice(0,10);state.fields.actDate=state.fields.measureDate=d;render();save()}if(t.id==='addFloorBtn'){const v=$('#floorName').value.trim();if(v){state.floors.push({id:uid(),name:v,rooms:[]});$('#floorName').value='';render();save()}}if(t.dataset.addRoom){const f=state.floors.find(x=>x.id===t.dataset.addRoom),i=$(`[data-room-input="${f.id}"]`);if(i.value.trim()){f.rooms.push({id:uid(),name:i.value.trim(),devices:[]});render();save()}}if(t.dataset.addDevice){const[fid,rid]=t.dataset.addDevice.split('|'),f=state.floors.find(x=>x.id===fid),r=f.rooms.find(x=>x.id===rid),type=$(`[data-device-type="${rid}"]`).value,name=$(`[data-device-name="${rid}"]`).value.trim(),q=Math.max(1,+$(`[data-device-qty="${rid}"]`).value||1);for(let i=0;i<q;i++)r.devices.push(device(type,name||(TYPES[type].name+' '+(r.devices.filter(x=>x.type===type).length+1))));render();save()}if(t.dataset.removeDevice){const[fid,rid,did]=t.dataset.removeDevice.split('|'),r=state.floors.find(x=>x.id===fid).rooms.find(x=>x.id===rid);r.devices=r.devices.filter(x=>x.id!==did);render();save()}if(t.dataset.removeRoom){const[fid,rid]=t.dataset.removeRoom.split('|'),f=state.floors.find(x=>x.id===fid);if(confirm('Dzēst telpu un visas tās ierīces?')){f.rooms=f.rooms.filter(x=>x.id!==rid);render();save()}}if(t.dataset.removeFloor&&confirm('Dzēst stāvu, telpas un ierīces?')){state.floors=state.floors.filter(x=>x.id!==t.dataset.removeFloor);render();save()}if(t.dataset.addSpecial){state.special[t.dataset.addSpecial].push({id:uid(),name:'',value:'',result:'Atbilst'});renderMeasurements();save()}if(t.dataset.removeSpecial){const[k,id]=t.dataset.removeSpecial.split('|');state.special[k]=state.special[k].filter(x=>x.id!==id);renderMeasurements();save()}if(t.dataset.removeAttachment){const[k,id]=t.dataset.removeAttachment.split('|');state[k]=state[k].filter(x=>x.id!==id);renderAttachments();save()}if(t.id==='fillPreviousBtn'){const n=carryForwardLoopValues();renderMeasurements();save();toast(n?`Aizpildītas ${n} tukšas vērtības`:'Nebija tukšu vērtību, ko aizpildīt')}if(t.id==='previewBtn'){fillBeforeExport();$('#reportPreview').innerHTML=reportHTML();$('#previewDialog').showModal()}if(t.id==='closePreview')$('#previewDialog').close();if(t.id==='pdfBtn'){fillBeforeExport();$('#printRoot').innerHTML=reportHTML();setTimeout(()=>window.print(),200)}if(t.id==='docxBtn'){fillBeforeExport();exportDocx()}if(t.id==='backupBtn')download(new Blob([JSON.stringify(state)],{type:'application/json'}),filename('json'));if(t.id==='newBtn'&&confirm('Sākt jaunu atskaiti? Pašreizējie dati tiks dzēsti.')){state=defaults();render();save()}if(t.id==='installBtn'&&installPrompt){installPrompt.prompt();installPrompt=null;t.classList.add('hidden')}});
async function addImages(files,target,extra={}){for(const f of files)try{state[target].push({id:uid(),data:await compress(f),description:target==='photos'?$('#photoDescription').value:'',type:extra.type||'',current:'',result:'Atbilst'})}catch(e){toast('Vienu attēlu neizdevās pievienot')}renderAttachments();save();toast('Attēli pievienoti')}
$('#certificateInput').addEventListener('change',e=>addImages(e.target.files,'certificates'));$('#photoInput').addEventListener('change',e=>addImages(e.target.files,'photos',{type:$('#photoType').value}));$('#restoreInput').addEventListener('change',e=>{const r=new FileReader;r.onload=()=>{try{state=JSON.parse(r.result);render();save();toast('Rezerves kopija atvērta')}catch{toast('Fails nav derīgs')}};r.readAsText(e.target.files[0])});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').classList.remove('hidden')});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');load();
})();
