(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), fmt=d=>d?d.split('-').reverse().join('.'):'';
const TYPES={socket:{name:'Rozete',cable:'Cu 3x2,5',breaker:'B16',phases:1},light:{name:'Gaismeklis',cable:'Cu 3x1,5',breaker:'B13',phases:1},three:{name:'3F rozete',cable:'Cu 5x2,5',breaker:'C16',phases:3},equipment:{name:'Iekārta',cable:'Cu 3x2,5',breaker:'B16',phases:1},other:{name:'Cits',cable:'',breaker:'',phases:1}};
const MODS={iso:'Izolācijas pretestība',loop:'Cilpa fāze–nulle un īsslēguma strāva',continuity:'Zemējuma nepārtrauktība',earth:'Zemējuma kontūra pretestība',lightning:'Zibensaizsardzība'};
const defaults=()=>({version:4,fields:{customer:'',customerPhone:'',customerEmail:'',objectName:'',address:'',workArea:'Viss objekts',actDate:'',measureDate:'',temperature:'',humidity:'',worker:'Marks Elarts',workerPhone:'+371 27 655 228',workerEmail:'marks.elarts@gmail.com',meterName:'Fluke',meterType:'1653',meterSerial:'8619046',calibrationNo:'787595',thermalCamera:'FLIR C3-X',thermalSerial:'905028092',thermalCalibrationNo:'T1395K23'},mods:{iso:true,loop:true,continuity:true,earth:false,lightning:false},floors:[],special:{earth:[{id:uid(),name:'Zemējuma kontūrs',value:'',result:'Atbilst'}],lightning:[{id:uid(),name:'Zibensaizsardzības sistēmas elements',value:'',result:'Atbilst'}]},certificates:[],photos:[]});
let state=defaults(), saveTimer, installPrompt;
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function openDB(){return new Promise((ok,no)=>{const q=indexedDB.open('merijumi-db',1);q.onupgradeneeded=()=>q.result.createObjectStore('reports');q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}
async function save(){clearTimeout(saveTimer);$('#saveStatus').textContent='Saglabā...';saveTimer=setTimeout(async()=>{try{const db=await openDB(),tx=db.transaction('reports','readwrite');tx.objectStore('reports').put(state,'current');await new Promise((a,b)=>{tx.oncomplete=a;tx.onerror=()=>b(tx.error)});$('#saveStatus').textContent='Saglabāts telefonā'}catch(e){$('#saveStatus').textContent='Neizdevās saglabāt';console.error(e)}},250)}
async function load(){try{const db=await openDB(),tx=db.transaction('reports'),q=tx.objectStore('reports').get('current');const data=await new Promise((a,b)=>{q.onsuccess=()=>a(q.result);q.onerror=()=>b(q.error)});if(data)state=Object.assign(defaults(),data)}catch(e){console.error(e)}if(!state.fields.actDate){const d=new Date().toISOString().slice(0,10);state.fields.actDate=state.fields.measureDate=d}render()}
function device(type,name){const p=TYPES[type];return{id:uid(),type,name:name||p.name,cable:p.cable,breaker:p.breaker,board:'GSS',voltage:p.phases===3?'400/230':'230',phases:p.phases,iso:'>500',continuity:'<0.1',result:'Atbilst',short1:'',short2:'',short3:'',loop1:'',loop2:'',loop3:''}}
function render(){Object.entries(state.fields).forEach(([k,v])=>{const e=$(`[data-field="${k}"]`);if(e&&document.activeElement!==e)e.value=v});$('#heroTitle').textContent=state.fields.objectName||'Jauna elektromērījumu atskaite';renderChoices();renderBuilding();renderMeasurements();renderAttachments();validate()}
function renderChoices(){$('#measurementChoices').innerHTML=Object.entries(MODS).map(([k,n])=>`<label class="choice"><input type="checkbox" data-mod="${k}" ${state.mods[k]?'checked':''}><span><b>${esc(n)}</b></span></label>`).join('')}
function renderBuilding(){const root=$('#building');root.innerHTML=state.floors.map(f=>`<div class="floor"><div class="floor-head"><input value="${esc(f.name)}" data-floor-name="${f.id}" aria-label="Stāva nosaukums"><button class="small danger" data-remove-floor="${f.id}">Dzēst</button></div><div class="floor-body"><div class="inline-form"><input placeholder="Jauna telpa" data-room-input="${f.id}"><button data-add-room="${f.id}">Pievienot telpu</button></div>${f.rooms.map(r=>`<div class="room"><div class="room-head"><input value="${esc(r.name)}" data-room-name="${r.id}"><button class="small danger" data-remove-room="${f.id}|${r.id}">Dzēst</button></div><div>${r.devices.map(d=>`<div class="device-chip"><span><b>${esc(d.name)}</b> · ${esc(TYPES[d.type]?.name||'Ierīce')}</span><button class="danger" data-remove-device="${f.id}|${r.id}|${d.id}">Dzēst</button></div>`).join('')||'<p class="hint">Nav ierīču.</p>'}</div><div class="add-device"><input placeholder="Ierīces nosaukums" data-device-name="${r.id}"><select data-device-type="${r.id}">${Object.entries(TYPES).map(([k,p])=>`<option value="${k}">${p.name}</option>`).join('')}</select><input type="number" min="1" value="1" data-device-qty="${r.id}" aria-label="Daudzums"><button data-add-device="${f.id}|${r.id}">Pievienot</button></div></div>`).join('')}</div></div>`).join('')||'<p class="hint">Pievieno pirmo stāvu.</p>'}
function allDevices(){return state.floors.flatMap(f=>f.rooms.flatMap(r=>r.devices.map(d=>({f,r,d}))))}
function renderMeasurements(){const root=$('#measurements'), enabled=state.mods.iso||state.mods.loop||state.mods.continuity;root.innerHTML=enabled?state.floors.map(f=>f.rooms.map(r=>r.devices.length?`<div class="measurement-room"><h3>${esc(f.name)} · ${esc(r.name)}</h3>${r.devices.map(d=>`<div class="measure-card"><div class="measure-title"><b>${esc(d.name)}</b><span>${esc(TYPES[d.type]?.name)}</span></div><div class="measurement-fields"><label>Sadalne<input data-dev="${d.id}|board" value="${esc(d.board)}"></label><label>Kabelis<input data-dev="${d.id}|cable" value="${esc(d.cable)}"></label><label>Aizsardzība<input data-dev="${d.id}|breaker" value="${esc(d.breaker)}"></label><label>Spriegums V<input data-dev="${d.id}|voltage" value="${esc(d.voltage)}"></label>${state.mods.iso?`<label>Izolācija MΩ<input data-dev="${d.id}|iso" value="${esc(d.iso)}"></label>`:''}${state.mods.continuity?`<label>PE saite Ω<input data-dev="${d.id}|continuity" value="${esc(d.continuity)}"></label>`:''}${state.mods.loop?phaseFields(d):''}<label>Atzinums<select data-dev="${d.id}|result"><option ${d.result==='Atbilst'?'selected':''}>Atbilst</option><option ${d.result==='Neatbilst'?'selected':''}>Neatbilst</option></select></label></div></div>`).join('')}</div>`:'').join('')).join(''):'<p class="hint">Ierīču mērījumu sadaļas nav izvēlētas.</p>';renderSpecial()}
function phaseFields(d){const fs=[1,...(d.phases===3?[2,3]:[])];return fs.map(n=>`<label>Iīss L${n} A<input inputmode="decimal" data-dev="${d.id}|short${n}" value="${esc(d['short'+n])}"></label><label>Zs L${n} Ω<input inputmode="decimal" data-dev="${d.id}|loop${n}" value="${esc(d['loop'+n])}"></label>`).join('')}
function renderSpecial(){let h='';for(const k of ['earth','lightning'])if(state.mods[k])h+=`<div class="measurement-room"><h3>${MODS[k]}</h3>${state.special[k].map(x=>`<div class="measure-card measurement-fields"><label>Vieta / elements<input data-special="${k}|${x.id}|name" value="${esc(x.name)}"></label><label>Pretestība Ω<input inputmode="decimal" data-special="${k}|${x.id}|value" value="${esc(x.value)}"></label><label>Atzinums<select data-special="${k}|${x.id}|result"><option ${x.result==='Atbilst'?'selected':''}>Atbilst</option><option ${x.result==='Neatbilst'?'selected':''}>Neatbilst</option></select></label><button class="danger" data-remove-special="${k}|${x.id}">Dzēst</button></div>`).join('')}<button class="secondary" data-add-special="${k}">Pievienot mērījuma vietu</button></div>`;$('#specialMeasurements').innerHTML=h}
function renderAttachments(){const cards=(a,type)=>a.map(x=>`<div class="thumb"><img src="${x.data}" alt=""><div class="thumb-body"><input value="${esc(x.description)}" data-attachment="${type}|${x.id}" aria-label="Apraksts"><button class="danger" data-remove-attachment="${type}|${x.id}">Dzēst</button></div></div>`).join('');$('#certificates').innerHTML=cards(state.certificates,'certificates');$('#photos').innerHTML=cards(state.photos,'photos')}
function validate(){const m=[];if(!state.fields.customer)m.push('nav pasūtītāja');if(!state.fields.address)m.push('nav adreses');if(!state.floors.length)m.push('nav stāvu');if(!allDevices().length)m.push('nav ierīču');if(!Object.values(state.mods).some(Boolean))m.push('nav izvēlētu mērījumu');$('#validation').className=m.length?'warn':'ok';$('#validation').textContent=m.length?'Pirms gala atskaites ieteicams aizpildīt: '+m.join(', ')+'.':'Pamatinformācija ir aizpildīta. Atskaiti var eksportēt.'}
function reportHTML(){const pages=[];pages.push(`<section class="report-page cover"><div class="cover-title"><h1>ELEKTROTEHNISKĀ DOKUMENTĀCIJA</h1><h2>${esc(state.fields.objectName||state.fields.address)}</h2></div><p class="cover-info"><b>Pasūtītājs:</b> ${esc(state.fields.customer)}<br><b>Objekts:</b> ${esc(state.fields.address)}<br><br><b>Mērījumus veica:</b> ${esc(state.fields.worker)}<br><b>Kontaktinformācija:</b> ${esc(state.fields.workerPhone)} · ${esc(state.fields.workerEmail)}</p></section>`);state.certificates.forEach((c,i)=>pages.push(`<section class="report-page certificate"><h3>Sertifikāts ${i+1}${c.description?' · '+esc(c.description):''}</h3><img src="${c.data}"></section>`));pages.push(actPage());if(state.mods.iso)pages.push(tablePage('1. Elektroinstalācijas izolācijas pretestības mērījumu rezultāti',isoTable()));if(state.mods.loop)pages.push(tablePage('2. Cilpas fāze–nulle pilnās pretestības un īsslēguma strāvas mērījumu rezultāti',loopTable()));if(state.mods.earth)pages.push(tablePage('3. Zemējumietaises pretestības mērījumu rezultāti',specialTable('earth')));if(state.mods.continuity)pages.push(tablePage('4. Zemējumvadu nepārtrauktības saites pretestības mērījumu rezultāti',continuityTable()));if(state.mods.lightning)pages.push(tablePage('5. Zibensaizsardzības sistēmas elementu pretestības mērījumu rezultāti',specialTable('lightning')));state.photos.forEach((p,i)=>pages.push(`<section class="report-page photo-page"><h2>${p.type==='thermal'?'Termogrāfiskais attēls':p.type==='scheme'?'Sadalnes shēma':'Fotoattēls'} nr. ${i+1}</h2><img src="${p.data}"><p><b>Apraksts:</b> ${esc(p.description||'—')}</p></section>`));return pages.join('')}
function actPage(){return `<section class="report-page"><h1>Elektroinstalācijas pārbaudes akts</h1><p><b>Akta sastādīšanas datums:</b> ${fmt(state.fields.actDate)}</p><p><b>Objekta atbildīgā persona:</b> ${esc(state.fields.customer)} ${esc(state.fields.customerPhone)}</p><p><b>Objekta nosaukums un adrese:</b> ${esc(state.fields.objectName)}, ${esc(state.fields.address)}</p><p><b>Darba norises vieta:</b> ${esc(state.fields.workArea)}</p><p><b>Darba veicējs:</b> ${esc(state.fields.worker)}</p><h3>Mēraparāta tehniskie dati</h3><table><tr><th>Nosaukums</th><th>Tips</th><th>Numurs</th><th>Kalibrēšanas sertifikāts</th></tr><tr><td>${esc(state.fields.meterName)}</td><td>${esc(state.fields.meterType)}</td><td>${esc(state.fields.meterSerial)}</td><td>${esc(state.fields.calibrationNo)}</td></tr><tr><td>${esc(state.fields.thermalCamera)}</td><td>Termokamera</td><td>${esc(state.fields.thermalSerial)}</td><td>${esc(state.fields.thermalCalibrationNo)}</td></tr></table><h3>Klimatiskie apstākļi</h3><table><tr><th>Datums</th><th>Temperatūra</th><th>Mitrums</th></tr><tr><td>${fmt(state.fields.measureDate)}</td><td>${esc(state.fields.temperature)}</td><td>${esc(state.fields.humidity)}%</td></tr></table><h3>Veiktie mērījumi</h3>${Object.entries(MODS).map(([k,n])=>`<p>${state.mods[k]?'☒':'☐'} ${n}</p>`).join('')}</section>`}
function rows(fn){let n=1,h='';state.floors.forEach(f=>f.rooms.forEach(r=>{if(!r.devices.length)return;h+=`<tr class="room-row"><td colspan="20">${esc(f.name)} · ${esc(r.name)}</td></tr>`;r.devices.forEach(d=>h+=fn(d,n++))}));return h}
const sig=()=>`<div class="signature"><p>Darba veicējs: ____________________<br>${esc(state.fields.worker)}</p><p>Akta eksemplāru saņēma: ____________________</p></div>`;
const tablePage=(title,table)=>`<section class="report-page"><h2>${title}</h2>${table}${sig()}</section>`;
function isoTable(){return `<table class="wide"><tr><th>Nr.</th><th>Atrašanās vieta / ierīce</th><th>Kabelis</th><th>U pārbaudes, V</th><th>L1-PE</th><th>L2-PE</th><th>L3-PE</th><th>N-PE</th><th>L1-N</th><th>L2-N</th><th>L3-N</th><th>Atzinums</th></tr>${rows((d,n)=>`<tr><td>${n}</td><td>${esc(d.name)}</td><td>${esc(d.cable)}</td><td>500</td><td>${esc(d.iso)}</td><td>${d.phases===3?esc(d.iso):''}</td><td>${d.phases===3?esc(d.iso):''}</td><td>${esc(d.iso)}</td><td>${esc(d.iso)}</td><td>${d.phases===3?esc(d.iso):''}</td><td>${d.phases===3?esc(d.iso):''}</td><td>${esc(d.result)}</td></tr>`)}</table>`}
function loopTable(){return `<table class="wide"><tr><th>Nr.</th><th>Atrašanās vieta / ierīce</th><th>Sadalne</th><th>U, V</th><th>Aizsardzība</th><th>Iīss L1</th><th>L2</th><th>L3</th><th>Zs L1</th><th>L2</th><th>L3</th><th>Atzinums</th></tr>${rows((d,n)=>`<tr><td>${n}</td><td>${esc(d.name)}</td><td>${esc(d.board)}</td><td>${esc(d.voltage)}</td><td>${esc(d.breaker)}</td><td>${esc(d.short1)}</td><td>${esc(d.short2)}</td><td>${esc(d.short3)}</td><td>${esc(d.loop1)}</td><td>${esc(d.loop2)}</td><td>${esc(d.loop3)}</td><td>${esc(d.result)}</td></tr>`)}</table>`}
function continuityTable(){return `<table><tr><th>Nr.</th><th>Atrašanās vieta / ierīce</th><th>Pretestība, Ω</th><th>Atzinums</th></tr>${rows((d,n)=>`<tr><td>${n}</td><td>${esc(d.name)}</td><td>${esc(d.continuity)}</td><td>${esc(d.result)}</td></tr>`)}</table>`}
function specialTable(k){return `<table><tr><th>Nr.</th><th>Vieta / elements</th><th>Pretestība, Ω</th><th>Atzinums</th></tr>${state.special[k].map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td>${esc(x.value)}</td><td>${esc(x.result)}</td></tr>`).join('')}</table>`}
async function compress(file){return new Promise((ok,no)=>{const r=new FileReader;r.onerror=no;r.onload=()=>{const im=new Image;im.onload=()=>{const max=1800,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext('2d').drawImage(im,0,0,c.width,c.height);ok(c.toDataURL('image/jpeg',.82))};im.onerror=no;im.src=r.result};r.readAsDataURL(file)})}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function filename(ext){return (state.fields.objectName||state.fields.address||'elektromerijumu_atskaite').replace(/[^\p{L}\p{N}]+/gu,'_').replace(/^_|_$/g,'')+'.'+ext}
async function exportDocx(){
  if(!window.docx){toast('DOCX modulis vēl nav ielādēts. Pārbaudi internetu.');return}
  toast('Veido DOCX failu...');
  const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,HeadingLevel,PageBreak,ImageRun,WidthType}=window.docx;
  const children=[];
  const p=(text,bold=false)=>new Paragraph({children:[new TextRun({text:String(text||''),bold})]});
  const cell=t=>new TableCell({children:[p(t)]});
  const table=(heads,data)=>new Table({width:{size:100,type:WidthType.PERCENTAGE},rows:[new TableRow({children:heads.map(cell),tableHeader:true}),...data.map(r=>new TableRow({children:r.map(cell)}))]});
  children.push(new Paragraph({text:'ELEKTROTEHNISKĀ DOKUMENTĀCIJA',heading:HeadingLevel.TITLE}),p(state.fields.objectName,true),p(state.fields.address),p(''),p('Pasūtītājs: '+state.fields.customer),p('Mērījumus veica: '+state.fields.worker),p(state.fields.workerPhone+' · '+state.fields.workerEmail));
  for(const c of state.certificates)children.push(new Paragraph({children:[new PageBreak()]}),new Paragraph({text:'Sertifikāts '+(c.description||''),heading:HeadingLevel.HEADING_1}),new Paragraph({children:[new ImageRun({data:dataBytes(c.data),transformation:{width:560,height:760},type:'jpg'})]}));
  children.push(new Paragraph({children:[new PageBreak()]}),new Paragraph({text:'Elektroinstalācijas pārbaudes akts',heading:HeadingLevel.TITLE}),p('Akta datums: '+fmt(state.fields.actDate)),p('Objekta atbildīgā persona: '+state.fields.customer),p('Objekts: '+state.fields.objectName+', '+state.fields.address),p('Darba norises vieta: '+state.fields.workArea),p('Darba veicējs: '+state.fields.worker),new Paragraph({text:'Mēraparāti',heading:HeadingLevel.HEADING_2}),table(['Nosaukums','Tips','Numurs','Sertifikāts'],[[state.fields.meterName,state.fields.meterType,state.fields.meterSerial,state.fields.calibrationNo],[state.fields.thermalCamera,'Termokamera',state.fields.thermalSerial,state.fields.thermalCalibrationNo]]),p(''),p('Veiktie mērījumi',true),...Object.entries(MODS).map(([k,n])=>p((state.mods[k]?'☒ ':'☐ ')+n)));
  const devs=allDevices();
  const section=(title,heads,map)=>children.push(new Paragraph({children:[new PageBreak()]}),new Paragraph({text:title,heading:HeadingLevel.HEADING_1}),table(heads,devs.map(({f,r,d},i)=>map(f,r,d,i))));
  if(state.mods.iso)section('Izolācijas pretestības mērījumi',['Nr.','Stāvs / telpa','Ierīce','Kabelis','MΩ','Atzinums'],(f,r,d,i)=>[i+1,f.name+' / '+r.name,d.name,d.cable,d.iso,d.result]);
  if(state.mods.loop)section('Cilpas fāze–nulle un īsslēguma strāvas mērījumi',['Nr.','Vieta','Ierīce','Sadalne','U','Aizsardzība','Iīss L1/L2/L3','Zs L1/L2/L3','Atzinums'],(f,r,d,i)=>[i+1,f.name+' / '+r.name,d.name,d.board,d.voltage,d.breaker,[d.short1,d.short2,d.short3].filter(Boolean).join(' / '),[d.loop1,d.loop2,d.loop3].filter(Boolean).join(' / '),d.result]);
  if(state.mods.continuity)section('Zemējuma nepārtrauktības mērījumi',['Nr.','Vieta','Ierīce','Ω','Atzinums'],(f,r,d,i)=>[i+1,f.name+' / '+r.name,d.name,d.continuity,d.result]);
  for(const k of ['earth','lightning'])if(state.mods[k])children.push(new Paragraph({children:[new PageBreak()]}),new Paragraph({text:MODS[k],heading:HeadingLevel.HEADING_1}),table(['Nr.','Vieta / elements','Ω','Atzinums'],state.special[k].map((x,i)=>[i+1,x.name,x.value,x.result])));
  for(let i=0;i<state.photos.length;i++){const x=state.photos[i];children.push(new Paragraph({children:[new PageBreak()]}),new Paragraph({text:(x.type==='thermal'?'Termogrāfiskais attēls':x.type==='scheme'?'Sadalnes shēma':'Fotoattēls')+' nr. '+(i+1),heading:HeadingLevel.HEADING_1}),new Paragraph({children:[new ImageRun({data:dataBytes(x.data),transformation:{width:560,height:420},type:'jpg'})]}),p('Apraksts: '+x.description))}
  const doc=new Document({sections:[{properties:{page:{margin:{top:720,right:720,bottom:720,left:720}}},children}]});
  download(await Packer.toBlob(doc),filename('docx'));toast('DOCX fails sagatavots');
}
function dataBytes(url){const b=atob(url.split(',')[1]),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
document.addEventListener('input',e=>{if(e.target.dataset.field)state.fields[e.target.dataset.field]=e.target.value;if(e.target.dataset.mod)state.mods[e.target.dataset.mod]=e.target.checked;if(e.target.dataset.floorName){const f=state.floors.find(x=>x.id===e.target.dataset.floorName);if(f)f.name=e.target.value}if(e.target.dataset.roomName){for(const f of state.floors){const r=f.rooms.find(x=>x.id===e.target.dataset.roomName);if(r)r.name=e.target.value}}if(e.target.dataset.dev){const[id,k]=e.target.dataset.dev.split('|'),x=allDevices().find(y=>y.d.id===id);if(x)x.d[k]=e.target.value}if(e.target.dataset.special){const[k,id,p]=e.target.dataset.special.split('|'),x=state.special[k].find(y=>y.id===id);if(x)x[p]=e.target.value}if(e.target.dataset.attachment){const[k,id]=e.target.dataset.attachment.split('|'),x=state[k].find(y=>y.id===id);if(x)x.description=e.target.value}save();validate()});
document.addEventListener('change',e=>{if(e.target.dataset.mod){renderMeasurements();save()}});
document.addEventListener('click',e=>{const t=e.target;if(t.id==='todayBtn'){const d=new Date().toISOString().slice(0,10);state.fields.actDate=state.fields.measureDate=d;render();save()}if(t.id==='addFloorBtn'){const v=$('#floorName').value.trim();if(v){state.floors.push({id:uid(),name:v,rooms:[]});$('#floorName').value='';render();save()}}if(t.dataset.addRoom){const f=state.floors.find(x=>x.id===t.dataset.addRoom),i=$(`[data-room-input="${f.id}"]`);if(i.value.trim()){f.rooms.push({id:uid(),name:i.value.trim(),devices:[]});render();save()}}if(t.dataset.addDevice){const[fid,rid]=t.dataset.addDevice.split('|'),f=state.floors.find(x=>x.id===fid),r=f.rooms.find(x=>x.id===rid),type=$(`[data-device-type="${rid}"]`).value,name=$(`[data-device-name="${rid}"]`).value.trim(),q=Math.max(1,+$(`[data-device-qty="${rid}"]`).value||1);for(let i=0;i<q;i++)r.devices.push(device(type,name||(TYPES[type].name+' '+(r.devices.filter(x=>x.type===type).length+1))));render();save()}if(t.dataset.removeDevice){const[fid,rid,did]=t.dataset.removeDevice.split('|'),r=state.floors.find(x=>x.id===fid).rooms.find(x=>x.id===rid);r.devices=r.devices.filter(x=>x.id!==did);render();save()}if(t.dataset.removeRoom){const[fid,rid]=t.dataset.removeRoom.split('|'),f=state.floors.find(x=>x.id===fid);if(confirm('Dzēst telpu un visas tās ierīces?')){f.rooms=f.rooms.filter(x=>x.id!==rid);render();save()}}if(t.dataset.removeFloor&&confirm('Dzēst stāvu, telpas un ierīces?')){state.floors=state.floors.filter(x=>x.id!==t.dataset.removeFloor);render();save()}if(t.dataset.addSpecial){state.special[t.dataset.addSpecial].push({id:uid(),name:'',value:'',result:'Atbilst'});renderMeasurements();save()}if(t.dataset.removeSpecial){const[k,id]=t.dataset.removeSpecial.split('|');state.special[k]=state.special[k].filter(x=>x.id!==id);renderMeasurements();save()}if(t.dataset.removeAttachment){const[k,id]=t.dataset.removeAttachment.split('|');state[k]=state[k].filter(x=>x.id!==id);renderAttachments();save()}if(t.id==='previewBtn'){const h=reportHTML();$('#reportPreview').innerHTML=h;$('#previewDialog').showModal()}if(t.id==='closePreview')$('#previewDialog').close();if(t.id==='pdfBtn'){$('#printRoot').innerHTML=reportHTML();setTimeout(()=>window.print(),200)}if(t.id==='docxBtn')exportDocx();if(t.id==='backupBtn')download(new Blob([JSON.stringify(state)],{type:'application/json'}),filename('json'));if(t.id==='newBtn'&&confirm('Sākt jaunu atskaiti? Pašreizējie dati tiks dzēsti.')){state=defaults();render();save()}if(t.id==='installBtn'&&installPrompt){installPrompt.prompt();installPrompt=null;t.classList.add('hidden')}});
async function addImages(files,target,extra={}){for(const f of files)try{state[target].push({id:uid(),data:await compress(f),description:target==='photos'?$('#photoDescription').value:'',type:extra.type||''})}catch(e){toast('Vienu attēlu neizdevās pievienot')}renderAttachments();save();toast('Attēli pievienoti')}
$('#certificateInput').addEventListener('change',e=>addImages(e.target.files,'certificates'));$('#photoInput').addEventListener('change',e=>addImages(e.target.files,'photos',{type:$('#photoType').value}));$('#restoreInput').addEventListener('change',e=>{const r=new FileReader;r.onload=()=>{try{state=JSON.parse(r.result);render();save();toast('Rezerves kopija atvērta')}catch{toast('Fails nav derīgs')}};r.readAsText(e.target.files[0])});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').classList.remove('hidden')});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');load();
})();
